### ISSUE TITLE
Installation imcomplete

### ISSUE THREAD

**Issue by pfeatherstone** [soumickmj/pytorch-complex#3]
If I either run:

```
pip3 install --upgrade git+https://github.com/soumickmj/pytorch-complex.git
```

or 

```
git clone https://github.com/soumickmj/pytorch-complex.git
cd pytorch-complex
python3 setup.py install
```

the ```utils``` subfolder does not get installed

**Comment by soumickmj** [comment]
Thanks for pointing it out and sorry for the long delay!
Git was having a missing push, it was one version behind, than the pip!
