### ISSUE TITLE
Complex weights

### ISSUE THREAD

**Issue by AVON257** [soumickmj/pytorch-complex#5]
I'd like to test this with complex weights set to true, as pytorch does supported that now.

Also wondering if this can be extended to other layer types, like LSTM ones.

**Comment by soumickmj** [comment]
Hey @AVON257 
Sorry I didn't respond to your issue earlier.
I have already changed complex_weights to True long back and is working fine for me.

I plan to implement LSTM and other layers as well, but haven't done that.
If you already have implemented, please feel free to contribute.
If not, I will do it in a while.

Thanks again for reaching out.
